### ISSUE TITLE
[Image Segmentation] Randomness in the fuzzy clustering algorithm

### ISSUE THREAD

**Issue by karlvmsousa** [karlvandesman/IN1102-Machine-Learning#12]
Since the initial values for the membership degree is selected randomly, every time that you run the algorithm, you'll get a different solution (based on this randomness). So, two approaches can be followed:

1. Use one specific seed (as a parameter for the predict function) to select a specific random state
1. A more interesting approach, select multiple random states, and based on the initial cost, continue with the best seed (that returned the lowest cost).

**Comment by karlvandesman** [comment]
resolved by 6611204

**Comment by karlvmsousa** [comment]
resolved by 6611204
