### ISSUE TITLE
Matriz de covariância

### ISSUE THREAD

**Issue by karlvmsousa** [karlvandesman/IN1102-Machine-Learning#2]
Será considerada a aproximação em que as covariância entre diferentes atributos é zero. Ou seja, os valores não-nulos serão somente os da diagonal, e assumindo um mesmo valor para todos os atributos.

```
classes, classes_num = np.unique(np.sort(dataset.index), return_counts=True)
k = len(classes)

varShape = dataShape.groupby(dataShape.index).var().var(axis=1)
varRGB = dataRGB.groupby(dataRGB.index).var().var(axis=1)

covShape = [ np.eye(np.size(dataShape, 1)) * varShape[i] for i in range(k) ]
covRGB = [ np.eye(np.size(dataRGB, 1)) * varRGB[i] for i in range(k) ]
```

**Comment by marciojr** [comment]
O cálculo foi realizado passando a diagonal da matriz de covariância de cada classes. Ou seja, passei um matriz de variância para cada feature da classe. 
```
for class_ in self.classes:
            class_mean = np.mean(classes[str(class_)],axis=0);
            class_cov = np.cov(classes[str(class_)],rowvar=False);

            mult_norm_dict.append(multivariate_normal(class_mean, np.diag(class_cov)));
```

Acho que vale observação ainda antes de fechar, mas acredito que esteja correto.
