### ISSUE TITLE
Criar classe para os classificadores

### ISSUE THREAD

**Issue by karlvmsousa** [karlvandesman/IN1102-Machine-Learning#4]
Modularizar o código, "empacotando" a parte de treinamento e previsão do classificador para posterior utilização.

Até agora estava implementando o classificador diretamente. Resta então criar uma classe usando cada parte do que já foi desenvolvido, e colocando métodos (_train_, _predict_).

**Comment by marciojr** [comment]
Realizando demanda.Vou ajustar pra ficar desta forma que falasse.

**Comment by karlvmsousa** [comment]
A forma que tava implementando era direta, aí não dá pra "reutilizar" a parte de treinamento e predição. Como estava escrevendo inicialmente as equações do modelo, não tinha me preocupado com essa parte. Pra rodar o RepeatedKFold (que eu já implementei, deixei lá separado...), vai precisar ficar utilizando como o treinamento/predição em um loop.

**Comment by marciojr** [comment]
Ação realizada. Modelos agora com classes e modularizadas.
